language: node_js
node_js:
  - 10.0.0
cache:
  directories:
    - "node_modules"
  yarn: true
env:
  - NODE_ENV = test
services:
  - postgresql

before_script:
  - npm run build && node dist/cli.js travis:ormConfig
  - node dist/cli.js migrations:up
  - bash ./scripts/database.travis.sh

after_success:
  - rm ./scripts/database.travis.sh

addons:
  postgresql: "9.6"
